#obj-y += fih_mem_hole.o
obj-y  += fih_usb.o
obj-y += fih_rere.o
obj-y += fih_apr.o
obj-y += fih_blog.o
obj-y += fih_bset.o
obj-y += fih_last_blog.o
obj-y += fih_hwid.o
obj-y += fih_info.o
obj-y += fih_emmc.o
obj-y += fih_dram.o
obj-y += fih_sut.o
obj-y += fih_fver.o
obj-y += fih_e2p.o
obj-y += fih_cda.o
obj-y += fih_cda_user.o
obj-y += fih_nv_rf.o
obj-y += fih_nv_cust.o
obj-y += fih_secboot.o
obj-y += fih_sensor.o
obj-y += fih_mdm_mp.o
obj-y += fih_touch.o
obj-y += fih_lcm.o
obj-y += fih_update_sku.o
obj-y += fih_update_sim.o
obj-y += fih_statusroot.o
obj-y += fih_cpu.o
obj-$(CONFIG_FIH_IPO) += fih_ipo.o
obj-y += fih_sd_status.o

obj-$(CONFIG_FIH_DEVICE_TREE_DEBUG) += dt_debug/
obj-$(CONFIG_FIH_HALL_SENSOR) += hallsensor/

obj-y += fih_camera_info.o
obj-y += fih_camera_dev.o
obj-y += fih_auth_key.o

obj-y += fih_simstate.o
obj-y += fih_simstate2.o
obj-y += fih_imei.o
obj-y += fih_skuid.o
obj-y += fih_imei2.o
obj-$(CONFIG_AWINIC_AW87319) += aw87319/
# SW4-HL-ForceTouch-BringUpTST241-00+_20160217
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP3_DEVICETREE_SUPPORT) += fih_forcetouch.o
obj-$(CONFIG_SHIRDA) += shirda/
