obj-$(CONFIG_SHIRDA) += shirda_ldisc.o
obj-$(CONFIG_SHIRDA) += wrapper.o
obj-$(CONFIG_SHIRDA) += shirda_msm_kdrv.o
obj-$(CONFIG_SHIRBLASTER) += shirb_ldisc.o

EXTRA_CFLAGS    +=  -DSHIRDA_CONFIG_H=\"shirda_kdrv_config_MSM8937.h\"
